### ISSUE TITLE
Is it possible to get fields UI when sign a document in DocuSign integration Android ?

### ISSUE THREAD

**Issue by RaziaSandhu** [docusign/docusign-android-starter-kit#2]

**Comment by mmallis87** [comment]
@RaziaSandhu Not sure I understand what do you mean by fields UI. Do you mean "embedded signing"?

By the way, for all DocuSign[ API] related questions, please post your question to Stackoverflow use "docusign" (or "docusignapi") tag. https://stackoverflow.com/questions/tagged/docusign

**Comment by RaziaSandhu** [comment]
hey i solved this. I just make x y position null and removed tabs. I got field UI on single tap on document

**Comment by mmallis87** [comment]
@RaziaSandhu I'm glad you've figured it out!
