### ISSUE TITLE
Docusign not working in production environment.

### ISSUE THREAD

**Issue by RaziaSandhu** [docusign/docusign-android-starter-kit#3]
I'm working on docusign integration in android. In sandbox mode it is doing good but in live doesn't working. 
In live environment it does not let me sign in and got no error msgs.
Please let me know if you know something about it.

**Comment by LarryKlugerDS** [comment]
You're probably using the wrong base URL. 
You obtain the base url differently depending on whether you're using OAuth or Legacy Authentication. [Documentation](https://docs.docusign.com/esign/guide/authentication/auth_overview.html)

**Comment by RaziaSandhu** [comment]
https://account.docusign.com/  
this my live base url

**Comment by LarryKlugerDS** [comment]
That's not correct. That is the host name used to initiate your OAuth flow. Then use the steps documented https://docs.docusign.com/esign/guide/authentication/oa2_auth_code.html to get your base URI for making your API calls.

Your base uri will be something like na2.docusign.net, na3.docusign.net, eu.docusign.net etc. 

Note the docs section Getting the User’s Account and Base URI Information

**Comment by RaziaSandhu** [comment]
https://www.docusign.net/restapi  for base url
and https://account.docusign.com/  for oauth base url

**Comment by RaziaSandhu** [comment]
according to https://www.docusign.com/developer-center/api-overview  url are correct

**Comment by LarryKlugerDS** [comment]
Please read the documentation about the base uri that I referenced above. You need to look up the base uri for the user's account. You look up the base uri by using an API method. See the docs about the base uri

**Comment by RaziaSandhu** [comment]
D/DocuSignOAuthService: https://account.docusign.com/oauth/token
W/System.err: java.io.FileNotFoundException: https://account.docusign.com/oauth/token
W/System.err:     at okhttp3.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
W/System.err:     at okhttp3.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:2
W/System.err:     at okhttp3.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
W/System.err:     at com.mortgage.MyDocuSign.service.DocuSignOAuthService.onHandleIntent(DocuSignOAuthService.java:86)
W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by RaziaSandhu** [comment]
I have used different servers still not working and got same error every time

**Comment by RaziaSandhu** [comment]
but in sandbox mode everything is working

**Comment by LarryKlugerDS** [comment]
Have you passed the go live certification to enable your Integration Key to work in production? See https://www.docusign.com/developer-center/api-overview#go-live

**Comment by RaziaSandhu** [comment]
yes my integrator key is in live mode

**Comment by RaziaSandhu** [comment]
Hey.
I have solved issue by changing scope "signature" to "all" and it is working.
