### ISSUE TITLE
Reload home page

### ISSUE THREAD

**Issue by khem88** [docusign/docusign-android-starter-kit#5]
Hi,

            After the login home page reload  again and again automatically . How to stop this?

   thanks.

**Comment by mmallis87** [comment]
Can you share some/all you login activity code? You may wanna obscure any private data.

**Comment by mmallis87** [comment]
Please check the latest commit.

**Comment by kak00n** [comment]
Hello!

I have the same error. 
I didn't  change anything in my login activity, i only add my CLIENT_ID in Config.java

In the other side, i dont know wath url redirect i must write in my configuration in Docusign, because i need to return to the app, isn`t it? For the moment i writed anything.
