### ISSUE TITLE
Regarding Docusign integration into my app

### ISSUE THREAD

**Issue by pravingaikwad07** [docusign/docusign-android-starter-kit#9]
I have my app where users will get a document that they need to e-sign and send back to the server.
How I can integrate DocuSign in such a way that end-user need not to login in DocuSign. They will just get a document from the server or opens a link into the app itself and sign in the doc using DocuSign and submit it.
Same goes to ios platform as well.
Can I achieve this ? 
I tried your sdk but I always need to login into your system.

**Comment by LarryKlugerDS** [comment]
Yes, you can have your back-end server obtain an access token for your app. Then, your app can create an envelope, create a signing ceremony view, and display the signing ceremony to the user.

The trick is to not have the user (the signer) authenticate. Instead, your backend server authenticates using a "system user" such as app@my_company.com. That way your app's users don't need an account on DocuSign.

If you want to enable signing while there is no Internet access, we have a specialized iOS SDK for that. We also have an Android SDK with the same feature, it's in beta. Let me know if you want access.

**Comment by pravingaikwad07** [comment]
Thanks for the response.
Is there any tutorial or documentation to implement this for Android and ios both? 
Thanks for suggesting the offline SDK but currently we are looking for an online-only solution.

**Comment by LarryKlugerDS** [comment]
Unfortunately, not at this time. The [Java launcher example](https://github.com/docusign/eg-03-java-auth-code-grant), in workflow 1 (embedded signing), demonstrates the general idea. But it does so using a server-based approach.
